using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using MovieWebApi.Dtos;
using MovieWebApi.Interfaces;
using MovieWebApi.Models;

namespace MovieWebApi.Services
{
    public class MovieService: IMovieService
    {
        private readonly IMovieRepository _repository;

        public MovieService(IMovieRepository repository)
        {
            _repository = repository;
        }
        public async Task<(IEnumerable<MovieDto> Movies, int TotalCount)> GetAllAsync(string? search = null, int? genreId = null, int pageNumber = 1, int pageSize = 10 , int? status = null)
        {
            var (movies , totalCount) = await _repository.GetAllAsync(search , genreId , pageNumber, pageSize , status);

            var movieDtos = movies.Select(movie => new MovieDto
            {
                Id = movie.Id,          
                Title = movie.Title,    
                Description = movie.Description, 
                Rating = movie.Rating,  
                ReleaseDate = movie.ReleaseDate, 
                Status = movie.Status,
                GenreId = movie.GenreId 
            });

            return (movieDtos, totalCount);
        }

        public async Task<MovieDto?> GetByIdAsync(int id)
        {
            var movie = await  _repository.GetByIdAsync(id);

            if (movie == null)
            {
                return null;
            }

            return new MovieDto
            {
                Id = movie.Id,
                Title = movie.Title,
                Description = movie.Description,
                Rating = movie.Rating,
                Status = movie.Status,
                ReleaseDate = movie.ReleaseDate,
                GenreId = movie.GenreId
            };

        }

        public async Task<MovieDto> CreateAsync(CreateMovieDto dto)
        {
            var movie = new Movie
            {
                Title = dto.Title,
                Description = dto.Description,
                Rating = dto.Rating,
                Status = dto.Status,
                ReleaseDate = dto.ReleaseDate,
                GenreId = dto.GenreId
            };
            await _repository.AddAsync(movie);
            await _repository.SaveChangesAsync(); 

            // 3. Return a response DTO (MovieDto) which includes the new ID generated by the database
            return new MovieDto
            {
                Id = movie.Id,
                Title = movie.Title,
                Description = movie.Description,
                Rating = movie.Rating,
                Status = movie.Status,
                ReleaseDate = movie.ReleaseDate,
                GenreId = movie.GenreId
            };
        }



        public async Task UpdateAsync(int id, UpdateMovieDto updateMovieDto)
        {
            var movie = await _repository.GetByIdAsync(id);

            if (movie == null) { return; }

            movie.Title = updateMovieDto.Title; 
            movie.Description = updateMovieDto.Description;
            movie.Rating = updateMovieDto.Rating;
            movie.Status = updateMovieDto.Status;
            movie.ReleaseDate = updateMovieDto.ReleaseDate;
            movie.GenreId = updateMovieDto.GenreId;

            _repository.Update(movie);
            await _repository.SaveChangesAsync();

        }

        public async Task DeleteAsync(int id)
        {
            var movie = await _repository.GetByIdAsync(id);

            if (movie != null) 
            { 
                  _repository.Delete(movie);
                await _repository.SaveChangesAsync();
            }

        }

        public async Task<MovieDto> DuplicateAsync(int id)
        {
            var movie = await _repository.GetByIdAsync(id);

            if (movie == null)
            {
                return null;
            }

            var newMovie = new Movie
            {
                Title = movie.Title,
                Description = movie.Description,
                Rating = movie.Rating,
                Status = movie.Status,
                ReleaseDate = movie.ReleaseDate,
                GenreId = movie.GenreId
            };

            await _repository.AddAsync(newMovie);
            await _repository.SaveChangesAsync();

            return new MovieDto
            {
                Id = newMovie.Id,
                Title = newMovie.Title,
                Description = newMovie.Description,
                Rating = newMovie.Rating,
                Status = newMovie.Status,
                ReleaseDate = newMovie.ReleaseDate,
                GenreId = newMovie.GenreId
            };
        }

    }
}
